### PR TITLE
Lab submission

### PR DESCRIPTION
**Pull request by el-besto**

### CODE REVIEW

**Comment by desa** [comment]
Any reason you just closed this now?

**Comment by el-besto** [comment]
Haha, Hi Mike - Wish I had a better answer for you, but the truth is that I just happened to be on my github and clicked on the Pull Requests tab and had A TON of them open. Sort of wanted to get them out of the way so NEXT time I happen to click on the PR tab it actually shows me those related to my work.

Anyways, how are things with you? Long time no talk! Did you end up finding a Go gig? How's Del? Still jumpin' around like a funky homosapien?

**Comment by desa** [comment]
Hey! Makes sense.

I'm good. I'm at InfluxDB now.

Del's good, he just got a new job at a place called blockscore. He's still jumpin' around like a funky homosapien.

We should get lunch sometime to catchup.

**Comment by el-besto** [comment]
Absolutely, I would love to. Where is your office? Im near Transamerica building. Good to know Del is still being his Del-ightful self!

**Comment by desa** [comment]
I'm near the Embarcadero south of Market.

**Pull request closed without merging**
